# .streamlit/config.toml

[theme]
# The main color for interactive elements
primaryColor = "#1f77b4"  # A nice muted blue

# Background color for the main content area
backgroundColor = "#f0f2f6"  # A light gray "litter shade"

# Background color for the sidebar and other secondary areas
secondaryBackgroundColor = "#e1e5eb" # A slightly darker gray

# Color for text
textColor = "#262730"

# Font family
font = "sans serif"